% read xy data from csv file generated by deeplabcut, then calculate velDat
function [xyDat,velDat]=readXYVelData(filename)
%read all data
datTmp=readmatrix(filename);
totalFrames=size(datTmp,1);
if totalFrames==0
    xyDat=[];
    velDat=[];
else
    totalSec=3600;       %assume 60min for each file
    frmRate=totalFrames/totalSec;   
    %use the first 3col (headmount-XY, and likelihood)
    xyDat=datTmp(:,1:3);
    %calculate velocity
    dt=1/frmRate;
    t=linspace(0,totalSec,totalFrames)';
    prePt=xyDat(:,1:2);
    prePt(2:end,:)=xyDat(1:end-1,1:2);
    vel0=sqrt((xyDat(:,1)-prePt(:,1)).^2+...
	    (xyDat(:,2)-prePt(:,2)).^2)./dt;  
    velDat=[t,vel0];
end